name: filterable_generator
description: A code generator for Filterable.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansi_styles: ^0.3.2+1
  build: ^2.4.1
  filterable_annotation:
    path: ../filterable_annotation
  source_gen: ^1.4.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^5.0.0
