name: firebase_filterable_adapter
description: A Flutter package that helps to use Filterable package with Firebase
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  cloud_firestore: ^4.9.1
  filterable:
    path: ../../filterable
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
